// M02-W07 WXT configuration: the manifest is generated by WXT from this
// configuration plus the two entrypoints — never hand-authored build
// output. The generated manifest is independently verified fail-closed by
// test/m02-w07/built-manifest.test.ts and by the real-browser E2E suite.
import { defineConfig } from "wxt";

export default defineConfig({
  // Explicit imports only: the W07 sources import WXT helpers directly, so
  // linting and typechecking work from a clean checkout without generated
  // auto-import state.
  imports: false,
  // Build output stays under the repository's ignored build-output
  // convention (dist/); WXT emits dist/chrome-mv3 for the chrome target.
  outDir: "dist",
  manifest: {
    // Neutral test-only naming (owner decision OD-003: no product name).
    name: "M02-W07 feasibility extension (test-only)",
    description:
      "Minimal Manifest V3 feasibility substrate for spec JAPP-MASTER-001 M02-W07. Loopback mock ATS probe only; no product behavior, no fill, no submit.",
    // No permissions, no host_permissions beyond the declared content
    // script match, no action/options/side-panel/devtools surface, no
    // externally_connectable. The built-manifest tests fail closed if any
    // such capability appears.
  },
});
