// M02-W11 WXT configuration: the manifest is generated by WXT from this
// configuration plus the two entrypoints — never hand-authored build
// output. The generated manifest is independently verified fail-closed by
// test/m02-w07/built-manifest.test.ts and by the real-browser E2E suite.
import { defineConfig } from "wxt";

export default defineConfig({
  // Explicit imports only: runtime sources import WXT helpers directly, so
  // linting and typechecking work from a clean checkout without generated
  // auto-import state.
  imports: false,
  // Build output stays under the repository's ignored build-output
  // convention (dist/); WXT emits dist/chrome-mv3 for the chrome target.
  outDir: "dist",
  manifest: {
    // Neutral test-only naming (owner decision OD-003: no product name).
    name: "M02-W11 dynamic reconciliation (test-only)",
    description:
      "Bounded Manifest V3 semantic scanner, transactional control-driver, and dynamic reconciliation feasibility harness for JAPP-MASTER-001 M02-W11. Permitted loopback frames only; no navigation execution or final-form action authority.",
    // No permissions, no host_permissions beyond the declared content
    // script match, no action/options/side-panel/devtools surface, no
    // externally_connectable. The built-manifest tests fail closed if any
    // such capability appears.
  },
});
