// M02-W07 built-manifest verification: runs the real WXT build, then
// independently inspects the generated Chrome MV3 output. These checks fail
// closed if the W07 scaffold ever gains product UI, privileged
// capabilities, broad host matches, or submission-shaped code (spec §1.5,
// REQ-FORM-011, REQ-FORM-025). The manifest is generated by WXT from
// wxt.config.ts plus the entrypoints — never hand-authored.
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, test } from "vitest";

import { FEASIBILITY_CONTENT_MATCH } from "../../src/feasibility-protocol.ts";

const PACKAGE_ROOT = fileURLToPath(new URL("../..", import.meta.url));
const BUILD_OUTPUT_DIR = join(PACKAGE_ROOT, "dist", "chrome-mv3");
const MANIFEST_PATH = join(BUILD_OUTPUT_DIR, "manifest.json");
const BUILD_TIMEOUT_MS = 180_000;

// The only top-level manifest members the W07 feasibility scaffold may
// declare. Any unexpected member — permissions, host_permissions, action,
// options_ui, side_panel, devtools_page, externally_connectable,
// web_accessible_resources, … — fails this suite; investigate the cause
// instead of extending the list.
const ALLOWED_TOP_LEVEL_KEYS = [
  "background",
  "content_scripts",
  "description",
  "manifest_version",
  "name",
  "version",
] as const;

// Capability-bearing manifest members that must never appear in W07.
const FORBIDDEN_TOP_LEVEL_KEYS = [
  "action",
  "browser_action",
  "chrome_url_overrides",
  "commands",
  "content_security_policy",
  "declarative_net_request",
  "devtools_page",
  "externally_connectable",
  "host_permissions",
  "oauth2",
  "optional_host_permissions",
  "optional_permissions",
  "options_page",
  "options_ui",
  "page_action",
  "permissions",
  "side_panel",
  "web_accessible_resources",
] as const;

// Submission/authority-shaped and network-egress code tokens that must not
// exist in the tracked runtime sources or the shipped bytes (no fill, no
// click, no submit, no credential/CAPTCHA/MFA handling, and no network
// channel of any kind in W07). The static egress tokens are the
// deterministic half of the network-isolation proof: the runtime request
// observation in e2e/extension cannot see requests issued inside the
// browser-launch window or non-HTTP channels, so shipped bytes must simply
// never contain an egress primitive.
const FORBIDDEN_CODE_TOKENS = [
  ".submit(",
  "requestSubmit",
  ".click(",
  "AUTO_SUBMIT",
  "credential",
  "captcha",
  "fetch(",
  "XMLHttpRequest",
  "WebSocket",
  "sendBeacon",
  "EventSource",
  "webkitRTC",
  "RTCPeerConnection",
] as const;

function resolveWxtBin(): string {
  const packageRequire = createRequire(join(PACKAGE_ROOT, "package.json"));
  const wxtEntry = packageRequire.resolve("wxt");
  // dist/index.mjs -> ../bin/wxt.mjs within the installed wxt package.
  const wxtBin = join(dirname(wxtEntry), "..", "bin", "wxt.mjs");
  if (!existsSync(wxtBin)) {
    throw new Error(`wxt CLI entry not found at ${wxtBin}`);
  }
  return wxtBin;
}

function readManifest(): Record<string, unknown> {
  const parsed: unknown = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("built manifest.json is not a JSON object");
  }
  return parsed as Record<string, unknown>;
}

function listFilesRecursively(root: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const absolute = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...listFilesRecursively(absolute));
    } else {
      files.push(absolute);
    }
  }
  return files;
}

beforeAll(() => {
  // Run the real pinned WXT build through the current Node binary (argv
  // array, no shell — portable across macOS/Windows/Ubuntu). The test owns
  // its build so `pnpm --filter @japp/extension test` is self-sufficient on
  // a clean checkout.
  execFileSync(process.execPath, [resolveWxtBin(), "build", "-b", "chrome"], {
    cwd: PACKAGE_ROOT,
    stdio: "pipe",
    timeout: BUILD_TIMEOUT_MS,
  });
}, BUILD_TIMEOUT_MS + 60_000);

describe("generated Chrome MV3 manifest", () => {
  test("the build produced a manifest at dist/chrome-mv3", () => {
    expect(existsSync(MANIFEST_PATH)).toBe(true);
  });

  test("manifest_version is genuinely 3", () => {
    expect(readManifest().manifest_version).toBe(3);
  });

  test("top-level members are exactly the reviewed W07 allowlist (fail closed on expansion)", () => {
    expect(Object.keys(readManifest()).sort()).toEqual([
      ...ALLOWED_TOP_LEVEL_KEYS,
    ]);
  });

  test("no capability-bearing manifest member is present", () => {
    const manifest = readManifest();
    for (const key of FORBIDDEN_TOP_LEVEL_KEYS) {
      expect(
        manifest,
        `capability member ${key} must be absent`,
      ).not.toHaveProperty(key);
    }
  });

  test("a real background service worker is declared and its file exists", () => {
    const manifest = readManifest();
    expect(manifest.background).toEqual({
      service_worker: "background.js",
    });
    const workerPath = join(BUILD_OUTPUT_DIR, "background.js");
    expect(existsSync(workerPath)).toBe(true);
    expect(statSync(workerPath).size).toBeGreaterThan(0);
  });

  test("exactly one content script exists, bounded to the loopback mock ATS origin", () => {
    const manifest = readManifest();
    expect(manifest.content_scripts).toEqual([
      {
        matches: [FEASIBILITY_CONTENT_MATCH],
        js: ["content-scripts/feasibility.js"],
      },
    ]);
    const scriptPath = join(
      BUILD_OUTPUT_DIR,
      "content-scripts",
      "feasibility.js",
    );
    expect(existsSync(scriptPath)).toBe(true);
    expect(statSync(scriptPath).size).toBeGreaterThan(0);
  });

  test("no broad host pattern is declared anywhere in the manifest", () => {
    const manifestText = readFileSync(MANIFEST_PATH, "utf-8");
    for (const broad of ["<all_urls>", "http://*/", "https://*/", "*://"]) {
      expect(manifestText).not.toContain(broad);
    }
  });

  test("the manifest identifies itself as the neutral test-only feasibility scaffold", () => {
    const manifest = readManifest();
    expect(manifest.name).toBe("M02-W07 feasibility extension (test-only)");
    expect(manifest.version).toBe("0.0.1");
  });
});

describe("no submission authority", () => {
  test("runtime sources and shipped bytes contain no submission-authority tokens", () => {
    const sources = [
      ...listFilesRecursively(join(PACKAGE_ROOT, "entrypoints")),
      ...listFilesRecursively(join(PACKAGE_ROOT, "src")),
      ...listFilesRecursively(BUILD_OUTPUT_DIR).filter((file) =>
        file.endsWith(".js"),
      ),
    ];
    expect(sources.length).toBeGreaterThanOrEqual(5);
    for (const file of sources) {
      const content = readFileSync(file, "utf-8").toLowerCase();
      for (const token of FORBIDDEN_CODE_TOKENS) {
        expect(content, `forbidden token ${token} in ${file}`).not.toContain(
          token.toLowerCase(),
        );
      }
    }
  });
});
